spring:
  cloud:
    sentinel:
      transport:
        #配置sentinel，dashboard地址
        dashboard: 192.168.36.128:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'